import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GN's Notes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-gray-900`}
      >
        {/* 🌟 Header with Note Link */}
        <header className="w-full p-4 bg-gray-100 text-center shadow-sm">
          <a
            href="https://note.com/gensnotes"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-600 font-semibold hover:underline text-lg"
          >
            📓 Check my Note blog
          </a>
        </header>

        {/* 🌈 Main Content */}
        <main className="max-w-3xl mx-auto px-4 py-8">{children}</main>

        {/* 🌙 Footer */}
        <footer className="w-full mt-12 p-4 text-center text-sm text-gray-400">
          © {new Date().getFullYear()} GN&apos;s Notes — Made with ❤️
        </footer>
      </body>
    </html>
  );
}